"""Models package for Phase 1 + Phase 2 Risk Management."""

from backend.models.requests import ChatRequest, Message
from backend.models.responses import ChatResponse, RiskAnalysisResponse
from backend.models.domain import (
    CommunicationRecord,
    DateRangeFilter,
    RiskInfo,
    RiskFramework,
)
from backend.models.conversation import (
    AgentType,
    ConversationMetadata,
    MessageRecord,
    CreateConversationRequest,
    CreateMessageRequest,
    CreateAgentRunLogRequest,
    AgentRunLog,
)

# Risk Management models (Phase 2)
from backend.models.risk_enums import (
    QualitativeScale,
    RiskCategory,
    RiskType,
    RiskNature,
    ActionType,
    LifecycleStatus,
    ReviewSessionType,
    ReviewSessionStatus,
    SourceLinkType,
    RiskRelationshipType,
    RiskActionLinkType,
    ActionEffectiveness,
    ActionEffort,
)
from backend.models.risk_domain import (
    RiskQualitativeAssessment,
    ActionQualitativeAssessment,
    RiskReviewSession,
    RiskActionLink,
    RiskSourceLink,
    ActionSourceLink,
    RiskRelationship,
    RiskReviewLog,
    SimilarRisk,
)
from backend.models.risk_requests import (
    CreateRiskRequest,
    UpdateRiskRequest,
    UpdateRiskStatusRequest,
    MarkReadyForRevisionRequest,
    ValidateRiskRequest,
    CreateActionRequest,
    UpdateActionRequest,
    StartReviewRequest,
    SubmitReviewRequest,
    TriggerRevisionRequest,
    CreateRiskActionLinkRequest,
    CreateRiskSourceLinkRequest,
    CreateRiskRelationshipRequest,
    RiskQueryFilters,
    ActionQueryFilters,
    SimilarRiskQuery,
    ReviewSessionQueryFilters,
)
from backend.models.risk_responses import (
    RiskResponse,
    RiskSummaryResponse,
    RiskListResponse,
    SimilarRiskResponse,
    ActionResponse,
    ActionSummaryResponse,
    ActionListResponse,
    LinkedRiskSummary,
    ReviewSessionResponse,
    StartReviewResponse,
    SubmitReviewResponse,
    PendingReviewResponse,
    PendingReviewListResponse,
    TriggerRevisionResponse,
    RiskActionLinkResponse,
    RiskSourceLinkResponse,
    RiskRelationshipResponse,
    RiskReviewLogResponse,
    RiskReviewLogListResponse,
    RiskWithRelationsResponse,
)
from backend.models.risk_review_metadata import (
    ReviewSummaryMetadata,
    ExtractedFeedback,
    AggregatedReviewFeedback,
    ReviewConversationContext,
    ReviewOpeningMessageMetadata,
    FeedbackExtractionInput,
    RevisionApplicationResult,
)
from backend.models.user_project import (
    UserProjectPurview,
    UserProjectAccess,
    ProjectTeamMember,
)

__all__ = [
    # API models (request/response)
    "ChatRequest",
    "ChatResponse",
    "Message",
    # Domain models (DTOs)
    "CommunicationRecord",
    "DateRangeFilter",
    # Risk models (legacy)
    "RiskInfo",
    "RiskFramework",
    "RiskAnalysisResponse",
    # Conversation models (database persistence)
    "AgentType",
    "ConversationMetadata",
    "MessageRecord",
    "CreateConversationRequest",
    "CreateMessageRequest",
    "CreateAgentRunLogRequest",
    "AgentRunLog",
    # Risk Management Enums (Phase 2)
    "QualitativeScale",
    "RiskCategory",
    "RiskType",
    "RiskNature",
    "ActionType",
    "LifecycleStatus",
    "ReviewSessionType",
    "ReviewSessionStatus",
    "SourceLinkType",
    "RiskRelationshipType",
    "RiskActionLinkType",
    "ActionEffectiveness",
    "ActionEffort",
    # Risk Management Domain Models (Phase 2)
    "RiskQualitativeAssessment",
    "ActionQualitativeAssessment",
    "RiskReviewSession",
    "RiskActionLink",
    "RiskSourceLink",
    "ActionSourceLink",
    "RiskRelationship",
    "RiskReviewLog",
    "SimilarRisk",
    # Risk Management Request Models (Phase 2)
    "CreateRiskRequest",
    "UpdateRiskRequest",
    "UpdateRiskStatusRequest",
    "MarkReadyForRevisionRequest",
    "ValidateRiskRequest",
    "CreateActionRequest",
    "UpdateActionRequest",
    "StartReviewRequest",
    "SubmitReviewRequest",
    "TriggerRevisionRequest",
    "CreateRiskActionLinkRequest",
    "CreateRiskSourceLinkRequest",
    "CreateRiskRelationshipRequest",
    "RiskQueryFilters",
    "ActionQueryFilters",
    "SimilarRiskQuery",
    "ReviewSessionQueryFilters",
    # Risk Management Response Models (Phase 2)
    "RiskResponse",
    "RiskSummaryResponse",
    "RiskListResponse",
    "SimilarRiskResponse",
    "ActionResponse",
    "ActionSummaryResponse",
    "ActionListResponse",
    "LinkedRiskSummary",
    "ReviewSessionResponse",
    "StartReviewResponse",
    "SubmitReviewResponse",
    "PendingReviewResponse",
    "PendingReviewListResponse",
    "TriggerRevisionResponse",
    "RiskActionLinkResponse",
    "RiskSourceLinkResponse",
    "RiskRelationshipResponse",
    "RiskReviewLogResponse",
    "RiskReviewLogListResponse",
    "RiskWithRelationsResponse",
    # Risk Review Metadata Models (Phase 2)
    "ReviewSummaryMetadata",
    "ExtractedFeedback",
    "AggregatedReviewFeedback",
    "ReviewConversationContext",
    "ReviewOpeningMessageMetadata",
    "FeedbackExtractionInput",
    "RevisionApplicationResult",
    # User Project Models (Phase 1.5.3)
    "UserProjectPurview",
    "UserProjectAccess",
    "ProjectTeamMember",
]
